language: generic

sudo: required

services:
  - docker

before_install:
  - docker build -t natekavyar/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true natekavyar/docker-react npm run test